name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
   build:
    runs-on: ubuntu-latest
    container: centos:7
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release && strip target/release/xenium-filter-transcripts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/xenium-filter-transcripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

